[package]
name = "cloud-identity-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }

# Web server framework
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }

# Serialization / Deserialization
serde = { version = "1", features = ["derive"] }

# Error handling
thiserror = "2.0"
color-eyre = "0.6"

# Configuration
config = "0.15"

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
reqwest = { version = "0.13", default-features = false, features = ["json"] }
