[workspace]
resolver = "2"

members = []

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace.lints.clippy]

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
invalid_html_tags = "deny"

[workspace.dependencies]
# Serialization / Deserialization
serde = "1"

# Error handling
color-eyre = "0.6"

# Configuration
config = "0.15"

# Logging and metrics
tracing = "0.1"

[package]
name = "cloud-identity-wallet"
version.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
serde_json = "1.0"
hex = "0.4"
hmac = "0.12"
thiserror = "2.0"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

color-eyre.workspace = true
config.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
reqwest = { version = "0.13", features = ["json"] }
time = { version = "0.3", features = ["serde", "macros", "serde-well-known"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[dev-dependencies]
reqwest = { version = "0.13", default-features = false, features = ["json"] }

[profile.dev]
# Speed up compilation time
debug = 1

[profile.release]
# Maximize runtime speed
codegen-units = 1
lto = "fat"
# Abort on panic
panic = "abort"
strip = "symbols"
